pull request from rlottie-2 team
Samsung/rlottie pull request #438
Opened 2020-10-03 14:46 UTC by innoinho

made 10 methods into rottieWasm.cpp

2020-10-14 01:24 UTC, rlottie requested changes
cleanup the patches .. squash them to a single commit . add only English description both in commit message as well as comments .

2020-10-19 04:51 UTC, hermet requested changes
You can extend the functionalities, but do you really need to modify original behaviors?

2020-10-19 04:51 UTC, hermet commented on 멘토링/0915.md
> +## 팀 소개
Doc in Korean is bad to oversea engineers.
This documentation shouldn't be involoved in this patch.

2020-10-19 04:51 UTC, hermet commented on src/wasm/rlottiewasm.cpp
> -const char *resource = "{\"v\":\"5.1.8\",\"fr\":60,\"ip\":3,\"op\":140,\"w\":500,\"h\":500,\"nm\":\"ANUB\",\"ddd\":0,\"assets\":[],\"layers\":[{\"ddd\":0,\"ind\":1,\"ty\":4,\"nm\":\"a\",\"sr\":1,\"ks
any reason you removed this?

2021-05-26 02:36 UTC, closed without merging

2021-05-26 02:37 UTC, smohantty commented
Not needed anymore